    <section class="py-10">
      <h2 class="font-[var(--font-heading)] text-[30px] font-semibold">Precisa de ajuda?</h2>
      <h4 class="mt-2 font-[var(--font-heading)] text-[26px] font-semibold">Dúvidas frequentes</h4>
      <h3 class="mt-2 text-base leading-relaxed">Abaixo as dúvidas mais frequentes, caso ainda persista a dúvida, entre em contato <b>clicando no icone do WhatsApp</b></h3>
      <div class="mt-6 space-y-2">
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">JÁ POSSUO UM SISTEMA, POSSO MIGRAR OS DADOS?</summary><p class="mt-2 text-sm text-white/90">Sim, podemos fazer a migração dos dados do seu antigo sistema, desde que tenhamos acesso a eles de forma organizada.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">JÀ TENHO UM SITE, POSSO USAR O SISTEMA VENDA DIRETA JUNTO COM MEU SITE, NO MESMO DOMÍNIO?</summary><p class="mt-2 text-sm text-white/90">Pode sim, criamos um sub-domínio dentro do seu seu site, ficando por exemplo: painel.seusite.com.br. Basta nos informar depois da compra que deseja usar um domínio já existente.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">JÁ TENHO UM PLANO DE NEGÓCIOS, É POSSÍVEL USÁ-LO?</summary><p class="mt-2 text-sm text-white/90">Sim, a instalação contempla a parametrização do seu plano de negócios.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">COMO EU VOU ADMNISTRAR O SISTEMA?</summary><p class="mt-2 text-sm text-white/90">O sistema possui um painel adminstrativo com diversos relatórios financeiros e podemos customizar diversos modelos a necessidade apresentada.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">QUAL É A TECNOLOGIA USADA NO SISTEMA?</summary><p class="mt-2 text-sm text-white/90">O sistema venda direta foi desenvolvido em PHP usando banco de dados MYSQL.</p><p class="mt-2 text-sm text-white/90">O sistema é hospedado nos USA em um servidor dedicado linux usando nginx e php 7.4.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">ALÉM DA MENSALIDADE, EXISTE OUTROS CUSTOS?</summary><p class="mt-2 text-sm text-white/90">Não temos taxas extras, poderá existir cobranças novas na medida em que o cliente peça novas funcionalidades, para isso existirá um acordo prévio.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">TEM INTEGRAÇÃO COM ERP?</summary><p class="mt-2 text-sm text-white/90">Nosso sistema de venda direta tem uma ótima flexibilidade para integrações, hoje temos um parceiro que é o Bling (sistema de gestão que descomplica o seu negócio.), mas podemos integrar com o seu ERP.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">POSSO USAR MINHA MARCA E MEU DOMINIO?</summary><p class="mt-2 text-sm text-white/90">Sim, um dos diferenciais deste sistema para venda direta é exatamente você utilizar o sistema personalizado com a marca de sua empresa.</p></details>
        <details class="rounded-lg border border-white/20 bg-white/5 p-4"><summary class="cursor-pointer font-semibold">COMO É FEITO O SUPORTE</summary><p class="mt-2 text-sm text-white/90">Oferecemos suporte direto pelo whatsapp e telefone.</p></details>
      </div>
    </section>
