services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coderush-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - coderush

  nginx:
    image: nginx:alpine
    container_name: coderush-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/bfr-artigo-map.conf:/etc/nginx/conf.d/00-bfr-map.conf
    depends_on:
      - app
    networks:
      - coderush

networks:
  coderush:
    driver: bridge
