    <section id="clientes" class="scroll-mt-28 py-10">
      <h4 class="font-[var(--font-heading)] text-[30px] font-semibold">Quem usa e recomenda!</h4>
      <div class="mt-2 h-1 w-[72px] rounded-full bg-white"></div>
      <h2 class="mt-4 font-[var(--font-heading)] text-xl font-semibold sm:text-2xl">Confira o que alguns clientes têm a dizer sobre o Sistema Venda Direta.</h2>
      <div class="mt-6 grid gap-4 md:grid-cols-2">
        <article class="rounded-2xl border border-white/20 bg-white/5 p-5"><p class="text-sm leading-relaxed text-white/90">Há mais de 8 anos usamos o sistema venda direta, que nos ajuda a gerenciar nossa rede de distribuidores e a aumentar nossas vendas com perfeição, eu recomendo! Já estamos a 8 anos aprimorando e crescendo, com um escritorio virtual simples para qualquer pessoa.</p><div class="mt-4 flex items-center gap-3"><img decoding="async" src="imagens/logo@2x-q5j2vw22ajhto7ptb6lous0grda1y29olapc310134.webp" alt="Ecotrend South América" class="h-10 w-10 rounded-full bg-white/15 p-1" loading="lazy" /><div><p class="font-semibold">Leandro Sato</p><p class="text-sm text-white/80">Ecotrend South America</p></div></div><p class="mt-3 text-base">★★★★★</p></article>
        <article class="rounded-2xl border border-white/20 bg-white/5 p-5"><p class="text-sm leading-relaxed text-white/90">Há 15 anos trabalhamos com a empresa SVD, manteve nosso sistema ERP legado de 2006 e reestruturou para novas versões, além de implementar novas funcionalidades. O sistema gerencia toda nossa operação, desde comercial ao faturamento.</p><div class="mt-4 flex items-center gap-3"><img decoding="async" src="imagens/logo_sistema-q5j2yjxlnn52kfujrc1mx3thco5hr6uayh8v191vgg.webp" alt="Emergency Doc Imob" class="h-10 w-10 rounded-full bg-white/15 p-1" loading="lazy" /><div><p class="font-semibold">Carlos Lemos</p><p class="text-sm text-white/80">Emergency Doc Imob</p></div></div><p class="mt-3 text-base">★★★★★</p></article>
        <article class="rounded-2xl border border-white/20 bg-white/5 p-5"><p class="text-sm leading-relaxed text-white/90">O sistema de MMN da empresa nos ajuda a gerenciar nossos distribuidores em todo o mundo. Trabalhamos com vários idiomas e moedas, com centros de distribuição em diferentes países. O módulo de centro de distribuição nos auxilia muito.</p><div class="mt-4 flex items-center gap-3"><img decoding="async" src="imagens/logo-1-q5j39t21h8jnkdi31p5u9rl5dqoowqim66f4vid6yo.webp" alt="Science Life" class="h-10 w-10 rounded-full bg-white/15 p-1" loading="lazy" /><div><p class="font-semibold">Alessandro</p><p class="text-sm text-white/80">Science Life</p></div></div><p class="mt-3 text-base">★★★★★</p></article>
        <article class="rounded-2xl border border-white/20 bg-white/5 p-5"><p class="text-sm leading-relaxed text-white/90">O sistema de Ecommerce da Sistema Venda Direta nos ajuda a gerenciar nossos clientes e vendas de vouchers. Contamos com módulos customizados de anti-fraude e controle de clientes. O sistema suporta o volume das promoções sem problemas.</p><div class="mt-4 flex items-center gap-3"><img decoding="async" src="imagens/341249332_244034884767561_2785740054709534699_n-150x150.webp" alt="SP Diversoões" class="h-10 w-10 rounded-full" loading="lazy" /><div><p class="font-semibold">Yoshiaki Shinagawa</p><p class="text-sm text-white/80">SP Diversões / Game Station</p></div></div><p class="mt-3 text-base">★★★★★</p></article>
      </div>
    </section>
